server:
  port: 8084
spring:
  datasource:
    url: jdbc:mysql://192.168.101.100:3306/gulimall_ums?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.101.100:8848
  application:
    name: gulimall-user
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml